name: Build and publish Release Candidate

on:
  push:
    branches:
      - 'test/flow'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Build internal release
        run: |
          ./gradlew clean
          echo \
            ${{ steps.buildnumber.outputs.build_number }} \
            "${{ steps.vars.outputs.major_version }}-internal-rc"